### ISSUE TITLE
Module not found: Error: Can't resolve '@angular/http'

### ISSUE THREAD

**Issue by blacar** [hipster-labs/generator-jhipster-entity-audit#84]
Trying to use this module with the lastest jhipster causes 

Module not found: Error: Can't resolve '@angular/http'

It seems The @angular/http is only available from RC versions of Angular2. Before it was angular2/http.

Are you plannign to fix this? ... any workaround?

**Comment by ruddell** [comment]
It's already fixed in master by https://github.com/hipster-labs/generator-jhipster-entity-audit/commit/994e57138a0e42cf9c3ffa7b6dccb34a8d9f139c#diff-7c5bbb0a6f54ec0f7d165e8f40a101a1, just needs a release.  

As a workaround until release, you can make the changes manually or install the npm module from Github.

**Comment by murdos** [comment]
Issue already fixed in master, and a new version should be released soon
